# Rabbit-mq Configuration
rabbit:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual-host: vhost-test
  publisher-return: true
  publisher-confirm-type: CORRELATED
  reconnect-consumer-time: 10000
  reconnect-consumer-tries: 0
  queue-properties:
    x-expires: 600000
    x-message-ttl: 300000
    x-queue-type: quorum
  ssl-enable: false